Upgraded CosmWasm runtime in Picasso to latest dependencies (#3677)
- allowed to run parity and cosmos rust code in same wasm contract and
fancy staff for precompiles
- updated host with host call depth
https://github.com/ComposableFi/cosmwasm-vm/pull/36
- removed reexport of cw std
- updated cw to version 1.2.+
- updated XCVM spec with interpetere != account, removed autogenerated
obsolete ToC, made more clear impl contracts vs logic , removed mosaic
died long ago
- renamed XCVM to XC as XCVM long and hard to type, and really it is
more about xc/swaps/mev rather than VM, which uses some VMs
- made features, std, no_std, right as i could
- forks will be replaced by forks into composablefi under
`<name>-no-std` later . all forks are PRs and issues on CW team repos
- unified deps into workspace deps
- started to use cw_serde fancy API to CW
- added XC to CI
- XCVM tests where failing with `cargo-package-build> thread
'tests::suite::cross_chain::test_simple_crosschain_xcvm_transfer'
panicked at 'Must be able ` which was before my commit anyway
- go over CW pallet guide - contracts work on Picasso


![image](https://github.com/ComposableFi/composable/assets/757125/3d5e1640-c5aa-4260-84c8-093c29fb82da)


- [x] PR title is my best effort to provide summary of changes and has
clear text to be part of release notes
- [x] I marked PR by `misc` label if it should not be in release notes
- [ ] I have linked Zenhub/Github or any other reference item if one
exists
- [x] I was clear on what type of deployment required to release my
changes (node, runtime, contract, indexer, on chain operation, frontend,
infrastructure) if any in PR title or description
- [ ] I waited and did best effort for `pr-workflow-check /
draft-release-check` to finish with success(green check mark) with my
changes
- [x] I have added at least one reviewer in reviewers list
- [ ] I tagged(@) or used other form of notification of one person who I
think can handle best review of this PR
- [x] I have proved that PR has no general regressions of relevant
features and processes required to release into production